### ISSUE TITLE
Fix 'Should fail to create George again' frontend test on Travis

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#110]
## Problem

For some reason this test [is timing out](https://travis-ci.org/okTurtles/group-income-simple/jobs/142130583), and nothing I've tried seems to fix it.

So for now we're just hackishly skipping it on Travis, but keeping it locally (as there's no problem on my machine with it).

This is its current hackish state:

``` js
    it('Should fail to create George again', function () {
      if (process.env.TRAVIS) {
        // TODO: figure out why travis is timing out on this one!
        console.log('!! SKIPPING: Should fail to create George again')
        console.log('!! make sure to figure this one out!')
        return Promise.resolve('skipping')
      }
      return n.click('.signup button.submit')
      .wait(() => document.getElementById('serverMsg').className.indexOf('danger') !== -1)
      // .wait(() => document.getElementById('serverMsg').innerText !== '')
      // .evaluate(function () {
      //   var response = document.getElementById('serverMsg')
      //   return {
      //     err: response.className.indexOf('danger') !== -1,
      //     text: response.innerText
      //   }
      // })
      // .should.finally.containEql({err: true})
    })
```

Note: The commended stuff at the end is basically not needed cause it's effectively equivalent to the `wait` line about it.
## Solution

Figure it out.

**Comment by vijayee** [comment]
This seems to be caused by an error in the backend with lodash going unhandled. There is no failure case so there is no response and thus the request times out.

**Comment by taoeffect** [comment]
@vijayee FYI, on my branch with Vue 1.x I'm still getting an error:

```
  Frontend
    ✓ Should start the backend server if necessary
    New user page
>> (node:42223) Warning: a promise was rejected with a non-error: [object Object]
      1) Should create user George


  15 passing (3s)
  2 pending
  1 failing

  1) Frontend New user page Should create user George:
     Error: the object {} was thrown, throw an Error :)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:502:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:559:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:604:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:679:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by taoeffect** [comment]
OK, weird, after upgarding nightmare I'm now seeing:

```
  Frontend
    ✓ Should start the backend server if necessary
    New user page
Req: /simple/signup, sending index.html for: dist/simple/signup
      ✓ Should create user George (1706ms)
>> (node:42422) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: (0 , _lodash2.default)(...).pickBy is not a function
>> (node:42422) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      1) Should fail to create George again


  16 passing (5s)
  2 pending
  1 failing

  1) Frontend New user page Should fail to create George again:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
