### ISSUE TITLE
Figure out: "SQLITE_ERROR: no such table: HashToData"

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#163]
### Problem

Sometimes, not always, this error happens when performing the following operations:

1. `grunt dev`
2. Visit http://localhost:8000/simple/event-log
3. Click `Create Random Group`

Generates backend error:

```
Running "watch" task
Waiting...
Gruntfile.js: loading file with babel support: ./backend/index.js
API server running at: http://Alice.local:3000
[pubsub] LdTsnhq connected from: Forwarded { ip: '127.0.0.1', secure: false, port: 64148 }
{ Error: SQLITE_ERROR: no such table: HashToData
    at Client_SQLite3._query (group-income-simple/node_modules/knex/lib/dialects/sqlite3/index.js:138:12)
    at Client_SQLite3.query (group-income-simple/node_modules/knex/lib/client.js:189:17)
    at Runner.<anonymous> (group-income-simple/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at group-income-simple/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (group-income-simple/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (group-income-simple/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as bind] (group-income-simple/node_modules/knex/lib/interface.js:85:23)
    at Object.<anonymous> (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:582:31)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at QueryBuilder.execute (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:567:20)
    at QueryBuilder.then (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:398:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) errno: 1, code: 'SQLITE_ERROR' }
Error: SQLITE_ERROR: no such table: HashToData
    at Client_SQLite3._query (group-income-simple/node_modules/knex/lib/dialects/sqlite3/index.js:138:12)
    at Client_SQLite3.query (group-income-simple/node_modules/knex/lib/client.js:189:17)
    at Runner.<anonymous> (group-income-simple/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at group-income-simple/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (group-income-simple/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (group-income-simple/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as bind] (group-income-simple/node_modules/knex/lib/interface.js:85:23)
    at Object.<anonymous> (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:582:31)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at QueryBuilder.execute (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:567:20)
    at QueryBuilder.then (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:398:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
Debug: handler, error
    {"msec":88.0300489962101,"error":"insert into \"HashToData\" (\"hash\", \"value\") values ('QmfQ3XD4vTDQEKzQV87udCX1voFsMoGY9rPuzgmU7jpQg5', '{\"version\":\"0.0.1\",\"parentHash\":null,\"data\":{\"type\":\"Creation\",\"payload\":{\"version\":\"0.0.1\",\"creationDate\":\"2017-01-27T02:57:31.153Z\",\"groupName\":\"Group 83\",\"sharedValues\":\"Testing this software\",\"changePercentage\":82,\"openMembership\":false,\"memberApprovalPercentage\":30,\"memberRemovalPercentage\":11,\"incomeProvided\":1165,\"contributionPrivacy\":\"Very Private\",\"founderHashKey\":null},\"version\":\"0.0.1\"}}') - SQLITE_ERROR: no such table: HashToData","data":{"errno":1,"code":"SQLITE_ERROR","isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
Debug: internal, error
    Error: SQLITE_ERROR: no such table: HashToData
    at Client_SQLite3._query (group-income-simple/node_modules/knex/lib/dialects/sqlite3/index.js:138:12)
    at Client_SQLite3.query (group-income-simple/node_modules/knex/lib/client.js:189:17)
    at Runner.<anonymous> (group-income-simple/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at group-income-simple/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (group-income-simple/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (group-income-simple/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as bind] (group-income-simple/node_modules/knex/lib/interface.js:85:23)
    at Object.<anonymous> (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:582:31)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at QueryBuilder.execute (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:567:20)
    at QueryBuilder.then (group-income-simple/node_modules/objection/lib/queryBuilder/QueryBuilder.js:398:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

### Solution

Unclear.

For now, anytime this page is being manually tested, run `grunt dev` like this:

```
$ DEBUG=knex:* grunt dev
```

When the error does not appear, the Knex debugging output clearly shows `HashToData` being created:

```
Running "watch" task
Waiting...
Gruntfile.js: loading file with babel support: ./backend/index.js
  knex:pool INFO pool sqlite3:sqlite3:client0 - dispense() clients=1 available=0 +0ms
API server running at: http://Alice.local:3000
  knex:client acquired connection from pool: __knexUid1 +299ms
  knex:query create table if not exists "HashToData" ("hash" text, "value" text not null, primary key ("hash")) +7ms
  knex:bindings [] +0ms
  knex:client releasing connection to pool: __knexUid1 +9ms
  knex:pool INFO pool sqlite3:sqlite3:client0 - dispense() clients=0 available=1 +0ms
```

The question is: does it *also* show it being created when the error does appear? Or does Knex output something else?

**Comment by taoeffect** [comment]
Done in #166.
